name: Build Image

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: image name
      tag:
        type: string
        required: false
        description: image tag
        default: latest
      context:
        type: string
        required: true
        description: context to build in

  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: image name
      tag:
        type: string
        required: false
        description: image tag
        default: latest
      context:
        type: string
        required: true
        description: context to build in

jobs:
  build:
    name: Build
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - working-directory: ${{ inputs.context }}
        run: |
          docker build -t ${{ inputs.name }}:${{ inputs.tag }} ${{ inputs.context }}
          docker push ${{ inputs.name }}:${{ inputs.tag }}
