name: Build home-assistant

on:
  push:
    branches:
      - master
    paths:
      - './home-assistant/**'
      - ./.github/workflows/home-assistant.yml

jobs:
  build:
    uses: ./.github/workflows/build.yml
